language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - cd ..
  - git clone https://github.com/owncloud/core.git
  - mv chat core/apps/
  - cd core
  - git submodule init
  - git submodule update
  - cd apps/chat

script:
#  - phpunit --coverage-clover=coverage.clover tests/
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover